########## Client configuration ##########
server_addrs = []

[policy]
# Force ticket delegation when not explicitly allowed by KDC policy
force_delegate = false

########## Server configuration ##########

[ticket]
# Specify the encryption type used when forging new tickets
cipher = "aes256-sha1"
# Specify the flags used when forging new tickets
flags = "FR"
# Specify the lifetime used when forging new tickets
lifetime = "10h"
# Specify the renewable lifetime used when forging new tickets
renewable_lifetime = "7d"
# Specify the minimum lifetime required when looking up tickets
minimum_lifetime = "5m"
# Use fully qualified usernames when forging tickets
fully_qualified_user = false
# Generate a cross-realm ticket instead of a regular one
cross_realm = false

[[acl]]
# Allow requests based on specific principal name regexp
principal = ""
# Allow requests based on specific user name regexp
user = ""
# Allow requests based on specific group membership regexp
group = ""
# Allow requests based on specific host network cidr
hosts = []
[acl.permissions]
# Permission to kinit
kinit = false
# Permission to fetch and list
read = false
# Permission to store and delete
write = false
# Permission to masquerade as any user
masquerade = false
